package Model;

public enum IntentionalElementLinkType {
    REFINEMENT_AND,
    REFINEMENT_OR,
    NEEDEDBY,
    QUALIFICATION,
    CONTRIBUTION_HELP,
    CONTRIBUTION_MAKE,
    CONTRIBUTION_HURT,
    CONTRIBUTION_BREAK
}
